---
- name: Upload nginx config files to server
  ansible.posix.synchronize:
    src: /contents/etc/nginx
    dest: /etc/

- name: Set file owner and permissions
  ansible.builtin.file:
    path: /etc/nginx
    owner: root
    group: root
    #mode: u=rwx,g=rwx,o=rwx
    recurse: true

- name: Rotate nginx log
  ansible.builtin.copy:
    content: ''
    dest: "{{ item }}"
    owner: www-data
    group: adm
    mode: '0644'
    backup: true
  loop:
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log
