---
- name: Upload nginx config files to server
  ansible.posix.synchronize:
    src: /contents/home/isucon/isuumo
    dest: /home/isucon/

- name: Set file owner and permissions
  ansible.builtin.file:
    path: /home/isucon/isuumo
    owner: isucon
    group: isucon
    #mode: u=rwx,g=rwx,o=rwx
    recurse: true

- name: Build Go App
  ansible.builtin.shell:
    cmd: source ~/.bashrc && make all
    chdir: /home/isucon/isucari/webapp/go
    executable: /bin/bash
  become: true
  become_user: isucon
  register: result
  changed_when: "'Nothing to be done' not in result.stdout"
