---
- name: Stop all services
  hosts: all
  become: true
  strategy: ansible.builtin.free
  tasks:
    - name: Stop systemd services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        # - isuumo.go
        - mysql
        - nginx

    - name: Setup proxy
      ansible.builtin.import_tasks:
        file: tasks/prepare_bench/setup_proxy.yaml
      when: "'proxy' in group_names"

    - name: Setup app
      ansible.builtin.import_tasks:
        file: tasks/prepare_bench/setup_app.yaml
      when: "'app' in group_names"

    - name: Setup db
      ansible.builtin.import_tasks:
        file: tasks/prepare_bench/setup_db.yaml
      when: "'db' in group_names"
