---
- name: Stop all services
  hosts: all
  become: true
  tasks:
    - name: Stop systemd services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        #- isuumo.go
        - mysql
        - nginx

- name: Setup proxy
  hosts: proxy
  become: true
  tasks:
    - name: Setup proxy
      ansible.builtin.import_tasks:
        file: tasks/prepare_bench/setup_proxy.yaml

- name: Setup app
  hosts: app
  become: true
  tasks:
    - name: Setup app
      ansible.builtin.import_tasks:
        file: tasks/prepare_bench/setup_app.yaml

- name: Setup db
  hosts: db
  become: true
  tasks:
    - name: Setup db
      ansible.builtin.import_tasks:
        file: tasks/prepare_bench/setup_db.yaml
